export const ErrorCodes = {
  // Collect stage
  COLLECT_SOURCE_TIMEOUT: "COLLECT_SOURCE_TIMEOUT",
  COLLECT_SOURCE_UNAVAILABLE: "COLLECT_SOURCE_UNAVAILABLE",
  COLLECT_PARSE_ERROR: "COLLECT_PARSE_ERROR",
  COLLECT_NO_ARTICLES: "COLLECT_NO_ARTICLES",

  // Analyze stage
  ANALYZE_API_ERROR: "ANALYZE_API_ERROR",
  ANALYZE_VALIDATION_ERROR: "ANALYZE_VALIDATION_ERROR",
  ANALYZE_TIMEOUT: "ANALYZE_TIMEOUT",
  ANALYZE_EMPTY_INPUT: "ANALYZE_EMPTY_INPUT",

  // Publish stage
  PUBLISH_CHANNEL_ERROR: "PUBLISH_CHANNEL_ERROR",
  PUBLISH_ALL_CHANNELS_FAILED: "PUBLISH_ALL_CHANNELS_FAILED",
  PUBLISH_DUPLICATE: "PUBLISH_DUPLICATE",

  // System
  SYSTEM_CONFIG_ERROR: "SYSTEM_CONFIG_ERROR",
  SYSTEM_UNEXPECTED: "SYSTEM_UNEXPECTED",

  // Admin / Pipeline
  PIPELINE_ALREADY_RUNNING: "PIPELINE_ALREADY_RUNNING",
  RUN_NOT_FOUND: "RUN_NOT_FOUND",
  ITEM_NOT_FOUND: "ITEM_NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  DB_CONNECTION_ERROR: "DB_CONNECTION_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
