spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/economic_briefing?stringtype=unspecified
    username: ${user.name}
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false

briefing:
  scheduler:
    enabled: false
