package com.economicbriefing.economicflow;

public enum EventRelationType {
    CAUSE, PURPOSE, RESPONSE, CONDITION, MOTIVATION,
    PREVIOUS_VERSION, SUPERSEDED_BY, STRENGTHENED_BY, RELAXED_BY,
    RESPONSE_TO, FOLLOW_UP, RELATED_TO, STATE_CHANGED_TO,
    DIRECT_CAUSE, EXPECTED_EFFECT
}
