package com.economicbriefing.economicflow;

public enum EventType {
    POLICY_CHANGE, POLICY_ANNOUNCEMENT, POLICY_REVIEW,
    RATE_CHANGE, RATE_DECISION, SYSTEM_CHANGE, TAX_CHANGE,
    INDICATOR_CHANGE, INDICATOR_TREND, INDICATOR_MILESTONE, FORECAST_CHANGE, MARKET_EVENT,
    INDUSTRY_CHANGE, CORPORATE_RESTRUCTURING, INTERNATIONAL_EVENT, GOVERNMENT_RESPONSE
}
